INSERT INTO category (abbreviation, description, monthly_limit, creation_date, last_update, active, category_type) values ('WYP', 'Jamużna z kurwowni', 5900, NOW(), NOW(), true, 1);
INSERT INTO category (abbreviation, description, monthly_limit, creation_date, last_update, active, category_type) values ('ZWO', 'Zwort długu', 0, NOW(), NOW(), true, 1);
INSERT INTO category (abbreviation, description, monthly_limit, creation_date, last_update, active, category_type) values ('LOK', 'Czynsz za wynajem mieszkania na Maciejewicza 35/3', 0, NOW(), NOW(), true, 1);
INSERT INTO category (abbreviation, description, monthly_limit, creation_date, last_update, active, category_type) values ('DIZ', 'Dieta na delegacji - zaliczka', 0, NOW(), NOW(), true, 1);
INSERT INTO category (abbreviation, description, monthly_limit, creation_date, last_update, active, category_type) values ('DIR', 'Dieta na delegacji - rozliczenie', 0, NOW(), NOW(), true, 1)
INSERT INTO category (abbreviation, description, monthly_limit, creation_date, last_update, active, category_type) values ('FOT', 'Fotografia i związany szrot', 0, NOW(), NOW(), true, 0);
INSERT INTO category (abbreviation, description, monthly_limit, creation_date, last_update, active, category_type) values ('MUL', 'Filmy, gry, muzyka, oprogramowanie, multimedia', 0, NOW(), NOW(), true, 0);
INSERT INTO category (abbreviation, description, monthly_limit, creation_date, last_update, active, category_type) values ('ZAS', 'Pożyczka zassana', 0, NOW(), NOW(), true, 1);
INSERT INTO category (abbreviation, description, monthly_limit, creation_date, last_update, active, category_type) values ('ZAZ', 'Zwrot pożyczki zassanej', 0, NOW(), NOW(), true, 0);
INSERT INTO category (abbreviation, description, monthly_limit, creation_date, last_update, active, category_type) values ('NAR', 'Narzędziai urządzenia kosmiczne', 0, NOW(), NOW(), true, 0);