<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="IncomeManagementService"
	targetNamespace="http://com.zwort/matahata/Services/1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns="http://com.zwort/matahata/Services/1"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

	<!-- types -->
	<wsdl:types>
		<xsd:schema targetNamespace="http://com.zwort/matahata/Services/1">
			<xsd:include schemaLocation="Service.xsd" />
		</xsd:schema>
	</wsdl:types>

<!-- 		<wsdl:message name="findAllIncomes"> -->
<!-- 	</wsdl:message> -->
	<wsdl:message name="addNewIncome">
		<wsdl:part name="addNewIncome" element="addNewIncome">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="addNewIncomeResponse">
		<wsdl:part name="addNewIncomeResponse" element="addNewIncomeResponse">
		</wsdl:part>
	</wsdl:message>
<!-- 	<wsdl:message name="findAllIncomesResponse"> -->
<!-- 		<wsdl:part name="findAllIncomesResponse" element="findAllIncomesResponse"> -->
<!-- 		</wsdl:part> -->
<!-- 	</wsdl:message> -->
	
	<!-- port type -->
	<wsdl:portType name="IncomeManagementPortType">
		<wsdl:operation name="addNewIncome">
			<wsdl:input name="addNewIncome" message="addNewIncome">
			</wsdl:input>
			<wsdl:output name="addNewIncomeResponse" message="addNewIncomeResponse">
			</wsdl:output>
		</wsdl:operation>
<!-- 		<wsdl:operation name="findAllIncomes"> -->
<!-- 			<wsdl:input name="findAllIncomes" message="findAllIncomes"> -->
<!-- 			</wsdl:input> -->
<!-- 			<wsdl:output name="findAllIncomesResponse" message="findAllIncomesResponse"> -->
<!-- 			</wsdl:output> -->
<!-- 		</wsdl:operation> -->
	</wsdl:portType>
	
	<!-- binding -->
	<wsdl:binding name="IncomeManagementServiceSoapBinding"
		type="IncomeManagementPortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="addNewIncome">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="addNewIncome">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="addNewIncomeResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
<!-- 		<wsdl:operation name="findAllIncomes"> -->
<!-- 			<soap:operation soapAction="" style="document" /> -->
<!-- 			<wsdl:input name="findAllIncomes"> -->
<!-- 				<soap:body use="literal" /> -->
<!-- 			</wsdl:input> -->
<!-- 			<wsdl:output name="findAllIncomesResponse"> -->
<!-- 				<soap:body use="literal" /> -->
<!-- 			</wsdl:output> -->
<!-- 		</wsdl:operation> -->
	</wsdl:binding>
	
	<!-- service -->
	<wsdl:service name="IncomeManagementService">
		<wsdl:port name="IncomeManagementPort" binding="IncomeManagementServiceSoapBinding">
			<soap:address location="http://localhost:9090/IncomeManagementPort" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>