<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="TransferManagementService"
	targetNamespace="http://com.zwort/matahata/Services/1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns="http://com.zwort/matahata/Services/1"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

	<!-- types -->
	<wsdl:types>
		<xsd:schema targetNamespace="http://com.zwort/matahata/Services/1">
			<xsd:include schemaLocation="Service.xsd" />
		</xsd:schema>
	</wsdl:types>

		<!-- messages -->
<!-- 	<wsdl:message name="findAllTransfers"> -->
<!-- 	</wsdl:message> -->
	<wsdl:message name="addNewTransfer">
		<wsdl:part name="addNewTransfer" element="addNewTransfer">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="addNewTransferResponse">
		<wsdl:part name="addNewTransferResponse" element="addNewTransferResponse">
		</wsdl:part>
	</wsdl:message>
<!-- 	<wsdl:message name="findAllTransfersResponse"> -->
<!-- 		<wsdl:part name="findAllTransfersResponse" element="findAllTransfersResponse"> -->
<!-- 		</wsdl:part> -->
<!-- 	</wsdl:message> -->
	
	<!-- port type -->
	<wsdl:portType name="TransferManagementPortType">
		<wsdl:operation name="addNewTransfer">
			<wsdl:input name="addNewTransfer" message="addNewTransfer">
			</wsdl:input>
			<wsdl:output name="addNewTransferResponse" message="addNewTransferResponse">
			</wsdl:output>
		</wsdl:operation>
<!-- 		<wsdl:operation name="findAllTransfers"> -->
<!-- 			<wsdl:input name="findAllTransfers" message="findAllTransfers"> -->
<!-- 			</wsdl:input> -->
<!-- 			<wsdl:output name="findAllTransfersResponse" message="findAllTransfersResponse"> -->
<!-- 			</wsdl:output> -->
<!-- 		</wsdl:operation> -->
	</wsdl:portType>
	
	<!-- binding -->
	<wsdl:binding name="TransferManagementServiceSoapBinding"
		type="TransferManagementPortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="addNewTransfer">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="addNewTransfer">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="addNewTransferResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
<!-- 		<wsdl:operation name="findAllTransfers"> -->
<!-- 			<soap:operation soapAction="" style="document" /> -->
<!-- 			<wsdl:input name="findAllTransfers"> -->
<!-- 				<soap:body use="literal" /> -->
<!-- 			</wsdl:input> -->
<!-- 			<wsdl:output name="findAllTransfersResponse"> -->
<!-- 				<soap:body use="literal" /> -->
<!-- 			</wsdl:output> -->
<!-- 		</wsdl:operation> -->
	</wsdl:binding>
	
	<!-- service -->
	<wsdl:service name="TransferManagementService">
		<wsdl:port name="TransferManagementPort" binding="TransferManagementServiceSoapBinding">
			<soap:address location="http://localhost:9090/TransferManagementPort" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>	